[
  {
    productTitle: "Nice black dress one",
    category: "fashion",
    ratingsandreviews: [],
    regularPrice: "200.00",
    salePrice: "189.99",
    sizes: ["S", "M", "L"],
    thumbnail: "https://flone-vue.pages.dev/img/product/fashion/1.jpg",
    thumbnails: [
      "https://flone-vue.pages.dev/img/product/fashion/1.jpg",
      "https://flone-vue.pages.dev/img/product/fashion/2.jpg",
      "https://flone-vue.pages.dev/img/product/fashion/1.jpg",
      "https://flone-vue.pages.dev/img/product/fashion/4.jpg",
      "https://flone-vue.pages.dev/img/product/fashion/5.jpg",
    ],
  },
  {
    productTitle: "Nice black dress two",
    category: "fashion",
    ratingsandreviews: [],
    regularPrice: "30.00",
    salePrice: "20.99",
    sizes: ["S", "M", "L", "XL"],
    thumbnail: "https://flone-vue.pages.dev/img/product/fashion/2.jpg",
    thumbnails: [
      "https://flone-vue.pages.dev/img/product/fashion/2.jpg",
      "https://flone-vue.pages.dev/img/product/fashion/4.jpg",
      "https://flone-vue.pages.dev/img/product/fashion/5.jpg",
    ],
  },
  {
    productTitle: "Nice black dress three",
    category: "Ladies",
    ratingsandreviews: [],
    regularPrice: "300.00",
    salePrice: "234.99",
    sizes: ["S", "M"],
    thumbnail: "https://flone-vue.pages.dev/img/product/fashion/3.jpg",
    thumbnails: [
      "https://flone-vue.pages.dev/img/product/fashion/3.jpg",
      "https://flone-vue.pages.dev/img/product/fashion/2.jpg",
      "https://flone-vue.pages.dev/img/product/fashion/4.jpg",
    ],
  },
  {
    productTitle: "Nice black dress four",
    category: "Ladies",
    ratingsandreviews: [],
    regularPrice: "0",
    salePrice: "22.49",
    sizes: ["S", "M", "L", "XXL"],
    thumbnail: "https://flone-vue.pages.dev/img/product/fashion/4.jpg",
    thumbnails: [
      "https://flone-vue.pages.dev/img/product/fashion/4.jpg",
      "https://flone-vue.pages.dev/img/product/fashion/2.jpg",
      "https://flone-vue.pages.dev/img/product/fashion/5.jpg",
    ],
  },
];
