export const ActionTypes = {
        SET_PRODUCTS: "SET_PRODUCTS",
        SET_CATEGORIES_AND_SIZES_PRODUCTS: "SET_CATEGORIES_AND_SIZES_PRODUCTS",
        SELECTED_PRODUCTS: "SELECTED_PRODUCTS",
        SET_WISHLIST_PRODUCTS: "SET_WISHLIST_PRODUCTS",
        SET_CARTLIST_PRODUCTS: "SET_CARTLIST_PRODUCTS",
        ADD_WISHLIST_PRODUCTS: "ADD_WISHLIST_PRODUCTS",
        REMOVE_SELECTED_PRODUCTS: "REMOVE_SELECTED_PRODUCTS"

}