export const ActionTypes = {
  SET_PRODUCTS: "SET_PRODUCTS",
  SET_CATEGORIES_AND_SIZES_PRODUCTS: "SET_CATEGORIES_AND_SIZES_PRODUCTS",
  SELECTED_PRODUCTS: "SELECTED_PRODUCTS",
  SET_WISHLIST_PRODUCTS: "SET_WISHLIST_PRODUCTS",
  SET_CARTLIST_PRODUCTS: "SET_CARTLIST_PRODUCTS",
  SET_MYORDERS: "SET_MYORDERS",
  ADD_WISHLIST_PRODUCTS: "ADD_WISHLIST_PRODUCTS",
  REMOVE_SELECTED_PRODUCTS: "REMOVE_SELECTED_PRODUCTS",
  ADD_TO_CART: "ADD_TO_CART",
  ADD_TO_WISH: "ADD_TO_WISH",
  REMOVE_CART_PRODUCT: "REMOVE_CART_PRODUCT",
  REMOVE_WISH_PRODUCT: "REMOVE_WISH_PRODUCT",
};
